"""Add course order FKs

Revision ID: 9be55490b84d
Revises: 797174627c57
Create Date: 2021-11-29 21:39:41.500058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be55490b84d'
down_revision = '797174627c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('top_course_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('second_course_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('third_course_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fourth_course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'course', ['fourth_course_id'], ['course_id'])
    op.create_foreign_key(None, 'user', 'course', ['top_course_id'], ['course_id'])
    op.create_foreign_key(None, 'user', 'course', ['third_course_id'], ['course_id'])
    op.create_foreign_key(None, 'user', 'course', ['second_course_id'], ['course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'fourth_course_id')
    op.drop_column('user', 'third_course_id')
    op.drop_column('user', 'second_course_id')
    op.drop_column('user', 'top_course_id')
    # ### end Alembic commands ###
