"""User relationship on progressrecord

Revision ID: d804a3be0d84
Revises: cf731788f82f
Create Date: 2021-11-27 20:40:15.190522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd804a3be0d84'
down_revision = 'cf731788f82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_record', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'progress_record', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress_record', type_='foreignkey')
    op.drop_column('progress_record', 'user_id')
    # ### end Alembic commands ###
