"""Initial commit

Revision ID: f25aa2e9cac6
Revises: 
Create Date: 2021-11-26 22:17:08.481079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25aa2e9cac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('progress_record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=False),
    sa.Column('stress_rating', sa.Integer(), nullable=False),
    sa.Column('positive_thinking_rating', sa.Integer(), nullable=False),
    sa.Column('recognize_stigma_rating', sa.Integer(), nullable=False),
    sa.Column('problem_solving_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('progress_record')
    op.drop_table('course')
    # ### end Alembic commands ###
